version: '3'

services:
  rabbitmq:
    container_name: rabbitmq-fullcycle
    image: rabbitmq:3-management
    ports: 
      - "5672:5672"
      - "15672:15672"
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest